// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLB9FiwOL4bxhLhAuw1Dbttog6zGP64Ik',
    appId: '1:82710032570:web:086ad59f9f18ec28601283',
    messagingSenderId: '82710032570',
    projectId: 'surveywebapp-e2987',
    authDomain: 'surveywebapp-e2987.firebaseapp.com',
    storageBucket: 'surveywebapp-e2987.appspot.com',
    measurementId: 'G-Z5PZF1BLET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-mj_4o0PeV3xM3N7V1sxJLi3vv8zWRE',
    appId: '1:82710032570:android:6cdc36ef12d75499601283',
    messagingSenderId: '82710032570',
    projectId: 'surveywebapp-e2987',
    storageBucket: 'surveywebapp-e2987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyghLf7VwrOAipVlRSI24gl1kDUmlnP60',
    appId: '1:82710032570:ios:c188ddac831f0756601283',
    messagingSenderId: '82710032570',
    projectId: 'surveywebapp-e2987',
    storageBucket: 'surveywebapp-e2987.appspot.com',
    iosClientId: '82710032570-kut1s0k62jmjq7rdlj2v6nuag72ocg7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveywebapp',
  );
}
